# version: '3.7'
# services:
#   postgres:
#     image: postgres:14 
#     restart: always
#     ports:
#       - "5432:5432"
#     environment:
#       - POSTGRES_USER='postgres'
#       - POSTGRES_PASSWORD='postgres'
#       - POSTGRES_DATABASE='postgres'
#     volumes:
#       - ./init/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
#       - ./init/fill_tables.sql:/docker-entrypoint-initdb.d/fill_tables.sql
      # - ./init/postgres-data:/var/lib/postgresql/data

version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
  api:
    container_name: quotes-api
    build:
      context: ./
      target: production
    image: quotes-api
    depends_on:
      - db
    ports:
      - 3000:3000
    environment:
      NODE_ENV: production
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: postgres
    links:
      - db
    volumes:
      - './:/src'
volumes:
  db:
    driver: local

