version: '3.7'
services:
  postgres:
    image: postgres:14 
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER='postgres'
      - POSTGRES_PASSWORD='postgres'
      - POSTGRES_DATABASE='postgres'
    volumes:
      - ./init/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
      - ./init/fill_tables.sql:/docker-entrypoint-initdb.d/fill_tables.sql
      # - ./init/postgres-data:/var/lib/postgresql/data

      
 
